[package]
name = "async_zmq"
version = "0.0.3"
authors = ["Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "WIP"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/wusyong/async-zmq"
documentation = "https://docs.rs/async-zmq"

[dependencies]
mio = "0.6.21"
zmq = "0.9.2"
async-std = "1.5.0"
futures-util = { version = "0.3.4", features = ["sink"] }

slab = "0.4.2"
once_cell = "1.3.1"

[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes", "unstable"] }
