[package]
name = "async_zmq"
version = "0.1.0"
authors = ["Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Async version for ZeroMQ bindings"
keywords = ["async", "bindings", "protocol", "zmq"]
categories = ["Asynchronous", "API bindings", "Concurrency", "Network programming"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/wusyong/async-zmq"
documentation = "https://docs.rs/async-zmq"

[dependencies]
mio = "0.6.21"
zmq = "0.9.2"
async-std = "1.5.0"
futures = "0.3.4"

slab = "0.4.2"
once_cell = "1.3.1"

[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes", "unstable"] }
