[package]
name = "async_zmq"
version = "0.0.2"
authors = ["Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "WIP"
license = "MIT/Apache-2.0"

[dependencies]
mio = "0.6.21"
zmq = "0.9.2"
anyhow = "1.0.27"
async-std = "1.5.0"

slab = "0.4.2"
once_cell = "1.3.1"