[package]
name = "async_zmq"
version = "0.0.1"
authors = ["Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "WIP"
license = "MIT/Apache-2.0"

[dependencies]
mio = "0.6.21"
zmq = "0.9.2"